# 校验节点软件系统及硬件系统、安装必要基础组件、docker、kubeadm、kubelet、kubectl
- hosts: 
  - new-master
  roles:
  - prepare/base
  - prepare/docker
  - prepare/kubernetes

# 进行apiserver负载均衡
- hosts: 
  - all
  roles:
  - role: load-balancer

# 分发 etcd client 证书
- hosts: 
  - etcd
  - kube-master
  - new-master
  roles:
  - etcd/certificates

# 生成master节点证书
- hosts: 
  - kube-master
  - new-master
  - kube-worker
  - new-worker
  roles:
  - kube-certificates

# 初始化master节点
- hosts: 
  - kube-master
  - new-master
  roles:
  - kube-master
  - kube-worker

# 标记各节点角色
- hosts: 
  - new-master
  roles:
  - post