- name: 判断 firewalld 是否安装
  shell: >
    systemctl status firewalld | grep active || echo "not be found"
  register: firewalld_already_installed

- name: 禁用防火墙
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: '"active" in firewalld_already_installed.stdout'
